version: '4.1'
services:
    main:
        container_name: Serve
        build:
            context: .
            dockerfile: /docker/php/Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - "8000:8000"

    mysql:
        image: mysql
        container_name: task-app-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tasks_app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - '3309:3306'
volumes:
    mysql:
        driver: "local"
